#!/bin/sh

restore_freebsd()
{
    # restore from backup original freebsd files
    cp -af /usr/local/share/@DISTRO_SAFE@/common-live-settings-@CODENAME_SAFE@/base/backup/* /
}

restore_packages_settings()
{
    # revert sudoers hack
    if [ -x /usr/local/bin/sudo ]; then
        sed -i "" "s@%wheel ALL=(ALL) ALL@# %wheel ALL=(ALL) ALL@" /usr/local/etc/sudoers
        sed -i "" "s@%sudo	ALL=(ALL) ALL@# %sudo	ALL=(ALL) ALL@" /usr/local/etc/sudoers
    fi

    update-alternatives --altdir /usr/local/etc/alternatives --remove htmlview /usr/local/bin/firefox
}

remove_files_from()
{
    for files in $(ls -l /usr/local/share/@DISTRO_SAFE@/common-live-settings-@CODENAME_SAFE@/etc/rc.d); do
        rm -f /etc/rc.d/$files
    done
}

case $2 in
    DEINSTALL)
    restore_freebsd
    restore_packages_settings
    remove_files_from
    ;;
    POST-DEINSTALL)
    #rm -Rf /usr/local/share/@DISTRO_SAFE@/common-live-settings-@CODENAME_SAFE@/
    echo "@DISTRO_SAFE@-live-common-settings-@CODENAME_SAFE@ was uninstalled."
    ;;
    *)
    echo $2
    ;;
esac

exit 0
