#!/bin/sh

case "$2" in
    POST-INSTALL)
    # copy dmrc from desktopbsd dir to /usr/share/skel
    cp -af /usr/local/share/desktopbsd/xfce-installed-settings-desktopbsd/etc/skel/dmrc /usr/share/skel/dot.dmrc

    # copy gtkrc-2.0 from desktopbsd dir to /usr/share/skel
    cp -af /usr/local/share/desktopbsd/xfce-installed-settings-desktopbsd/etc/skel/gtkrc-2.0 /usr/share/skel/dot.gtkrc-2.0
    
    # copy grub config 
    if [ ! -d /usr/local/etc/default ]; then
        mkdir -p /usr/local/etc/default
    fi
    cp -af /usr/local/share/desktopbsd/xfce-installed-settings-desktopbsd/etc/default/*   /usr/local/etc/default

    # copy xdg
    cp -af /usr/local/share/desktopbsd/xfce-installed-settings-desktopbsd/etc/xdg/*   /usr/local/etc/xdg
    
    # set x-terminal-emulator alternative for gksu
    if [ -e /usr/local/bin/xfce4-terminal ] ; then
        update-alternatives --altdir /usr/local/etc/alternatives --install /usr/local/bin/x-terminal-emulator x-terminal-emulator /usr/local/bin/xfce4-terminal 50
    fi
    ;;
esac

exit 0
