#!/bin/bash

WALLPAPER=desktopbsd
CODENAME_SAFE=desktopbsd
DISTRO=DesktopBSD
DISTRO_SAFE=desktopbsd
PORT_VERSION=1.0
ORGANIZATION=DesktopBSD

GTK_THEME=Ghomix
MATE_ICONSET=Vibrancy-Aqua-Dark
XFCE_ICONSET=Vibrancy-Aqua-Dark

# KDM theme
USE_THEME=true
KDE_THEME=DesktopBSD

# USER for 10-live-cd.pkla
DISTRO_USER=desktopbsd