#!/bin/bash

WALLPAPER=GreenLeaf
CODENAME_SAFE=Karine
DISTRO=GhostBSD
DISTRO_SAFE=ghostbsd
PORT_VERSION=1.0
ORGANIZATION=GhostBSD

GTK_THEME=Ghomix
MATE_ICONSET=Vibrancy-Aqua-Dark

# KDM theme
USE_THEME=true
KDE_THEME=whiteroom

# USER for 10-live-cd.pkla
GHOSTBSD_USER=ghostbsd
