#!/bin/sh

case "$2" in
    POST-INSTALL)
    # copy dmrc from @DISTRO_SAFE@ dir to /usr/share/skel
    cp -af /usr/local/share/@DISTRO_SAFE@/xfce-installed-settings-@CODENAME_SAFE@/etc/skel/dmrc /usr/share/skel/dot.dmrc

    # copy gtkrc-2.0 from @DISTRO_SAFE@ dir to /usr/share/skel
    cp -af /usr/local/share/@DISTRO_SAFE@/xfce-installed-settings-@CODENAME_SAFE@/etc/skel/gtkrc-2.0 /usr/share/skel/dot.gtkrc-2.0
    
    # copy grub config 
    if [ ! -d /usr/local/etc/default ]; then
        mkdir -p /usr/local/etc/default
    fi
    cp -af /usr/local/share/@DISTRO_SAFE@/xfce-installed-settings-@CODENAME_SAFE@/etc/default/*   /usr/local/etc/default

    # copy xdg
    cp -af /usr/local/share/@DISTRO_SAFE@/xfce-installed-settings-@CODENAME_SAFE@/etc/xdg/*   /usr/local/etc/xdg
    
    # set x-terminal-emulator alternative for gksu
    if [ -e /usr/local/bin/xfce4-terminal ] ; then
        update-alternatives --altdir /usr/local/etc/alternatives --install /usr/local/bin/x-terminal-emulator x-terminal-emulator /usr/local/bin/xfce4-terminal 50
    fi

    # User gtk-bookmarks.
    printf "file:///root/Documents Documents
file:///root/Downloads Downloads
file:///root/Movies Movies
file:///root/Music Music
file:///root/Pictures Pictures" > /root/.gtk-bookmarks

    mkdir -p /root/Documents
    mkdir -p /root/Downloads
    mkdir -p /root/Movies
    mkdir -p /root/Music
    mkdir -p /root/Pictures

    printf "file:///home/@GHOSTBSD_USER@/Documents Documents
file:///home/@GHOSTBSD_USER@/Downloads Downloads
file:///home/@GHOSTBSD_USER@/Movies Movies
file:///home/@GHOSTBSD_USER@/Music Music
file:///home/@GHOSTBSD_USER@/Pictures Pictures" > /home/@GHOSTBSD_USER@/.gtk-bookmarks

    chmod g+rwx /home/@GHOSTBSD_USER@/.gtk-bookmarks
    mkdir -p /home/@GHOSTBSD_USER@/Documents
    chmod g+rwx /home/@GHOSTBSD_USER@/Documents
    mkdir -p /home/@GHOSTBSD_USER@/Downloads
    chmod g+rwx /home/@GHOSTBSD_USER@/Downloads
    mkdir -p /home/@GHOSTBSD_USER@/Movies 
    chmod g+rwx /home/@GHOSTBSD_USER@/Movies
    mkdir -p /home/@GHOSTBSD_USER@/Music
    chmod g+rwx /home/@GHOSTBSD_USER@/Music
    mkdir -p /home/@GHOSTBSD_USER@/Pictures
    chmod g+rwx /home/@GHOSTBSD_USER@/Pictures
    ;;
esac

exit 0
